### ISSUE TITLE
Result of opt-msssim?

### ISSUE THREAD

**Issue by WangJY06** [xyq7/InvCompress#2]
Can you provide the results of opt-msssim as well?
Thanks

**Comment by xyq7** [comment]
Sure. For kodak dataset
{
    "name": "Proposed Method [MS-SSIM]",
    "description": "Inference (ans)",
    "results": {
      "psnr": [
        26.823659514330824,
        28.06343188715044,
        29.95932014643374,
        32.32638572610363,
        33.50780497087087
      ],
      "ms-ssim": [
        0.9662731513381004,
        0.9787184273203214,
        0.9895740623275439,
        0.9949360117316246,
        0.9965860843658447
      ],
      "bpp": [
        0.17329237196180558,
        0.2646993001302083,
        0.48674858940972227,
        0.8375481499565972,
        1.1070421006944444
      ]
    }
  }
