### ISSUE TITLE
Is it convenient to give a pre-trained model under higher compression

### ISSUE THREAD

**Issue by JXH-SHU** [xyq7/InvCompress#4]
Thanks for your last reply! When I try to train the model under higher compression (nearing 0.06), I get a poor performance. So do you have the pretrained model under higher compression ?

**Comment by xyq7** [comment]
Thanks for your question. We follow the suggested quality and corresponding lambda setting of CompressAI library, and we don't have other pretrained models.

**Comment by JXH-SHU** [comment]
Thank you！
