### ISSUE TITLE
Fail to load pretrained model

### ISSUE THREAD

**Issue by lep990816** [xyq7/InvCompress#6]
Hi, I try to load the pre-trained model and fine-tune it in my own dataset. However, there exists a bug in loading the model:

https://github.com/xyq7/InvCompress/blob/17deb0f0e2f28432e6d5b38d0898ead58ccbcde4/codes/examples/train.py#L444

In this line, there has an KeyError: 'state_dict'.

It seems that the model is not saved as train.py in line 501:

 save_checkpoint(
                {
                    "epoch": epoch + 1,
                    "state_dict": net.state_dict(),
                    "loss": loss,
                    "optimizer": optimizer.state_dict(),
                    "aux_optimizer": aux_optimizer.state_dict(),
                    "lr_scheduler": lr_scheduler.state_dict(),
                },
                is_best,
                os.path.join('../experiments', args.experiment, 'checkpoints', "checkpoint_%03d.pth.tar" % (epoch + 1))
            )

**Comment by xyq7** [comment]
Hi, thanks for your interest in our work.

To reduce storage, the released checkpoint only contains "state_dict". You can load it with

> net = architectures[args.model].from_state_dict(checkpoint)
