### ISSUE TITLE
Total patches

### ISSUE THREAD

**Issue by prmudgal** [xyq7/InvCompress#8]
Hello,

Great work and awesome code. Thank you very much for sharing.
I see that total 20,745 images are present in Flickr dataset out of which 200 random images are taken away for validation, and then generated patches of size 256*256. 
If I use the generate patch script, it results huge number of patches. How many patches are present in your training dataset? 

Regards
Priyanka

**Comment by xyq7** [comment]
Hello, 
thank you for your interest. The script filters images larger than 256 * 256. During training, we use one image only once in an epoch with random cropping to 256*256.
